version: '3'

# compose for run locally
services:
  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    entrypoint: npm start
